# -*- coding: utf-8 -*-
"""Rename_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nd0tWlR-msQQ2uQyH52XiesAD8Az0vdn
"""

from google.colab import drive
drive.mount('/content/drive')

"""**Kamiz**"""

import zipfile
from pathlib import Path
from tqdm import tqdm

# ========== CONFIGURATION ==========
ZIP_PATH = "/content/drive/MyDrive/rename/Train.zip"   # ← CHANGE THIS
OUTPUT_ROOT = "/content/kurti_renamed"        # Where renamed Kamiz will go
TARGET_CLASS = "kurti"                        # Top folder inside zip (case‑sensitive)
INTERMEDIATE_FOLDER = "Final Kurti+ Panjabi for Women"   # The folder after Kurti
# ===================================

def extract_and_rename_kamiz(zip_path, output_root, target_class):
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as zf:
        # Get all files that belong to: target_class / output / any_subfolder / image
        # We'll filter for paths that match pattern: Kamiz/output/*/*
        members = []
        for member in zf.infolist():
            if member.is_dir():
                continue
            parts = Path(member.filename).parts
            # Expected structure: ('train', 'Kamiz', 'output', 'subfolder', 'image.jpg')
            # or maybe no 'train' top? We'll be flexible: look for target_class then 'output'
            if len(parts) >= 4 and parts[0] == target_class and parts[1] == "output":
                members.append(member)
            # Also handle case where zip root is directly Kamiz (no 'train' folder)
            elif len(parts) >= 3 and parts[0] == target_class and parts[1] == "output":
                members.append(member)
            # Alternative: if there is a top-level 'train' folder:
            elif len(parts) >= 5 and parts[1] == target_class and parts[2] == "output":
                members.append(member)

        if not members:
            print(f"❌ No files found under '{target_class}/output/*/'. Check the zip structure.")
            print("Here are the first 20 entries in the zip for debugging:")
            with zipfile.ZipFile(zip_path, 'r') as zf_debug:
                for i, name in enumerate(zf_debug.namelist()[:20]):
                    print(f"  {name}")
            return

        # Counters per subfolder (e.g., folder1, folder2, ...)
        subfolder_counters = {}

        for member in tqdm(members, desc=f"Extracting {target_class}"):
            parts = Path(member.filename).parts
            # Find the subfolder name (the one directly under 'output')
            # Try to locate the index of 'output' in the path
            try:
                output_idx = parts.index("output")
                subfolder = parts[output_idx + 1]   # e.g., 'agnostic'
            except (ValueError, IndexError):
                print(f"Skipping unexpected path: {member.filename}")
                continue

            dest_dir = output_root / subfolder
            dest_dir.mkdir(parents=True, exist_ok=True)

            # Get next index for this subfolder
            if subfolder not in subfolder_counters:
                existing = len(list(dest_dir.glob("*")))
                subfolder_counters[subfolder] = existing + 1
            idx = subfolder_counters[subfolder]
            subfolder_counters[subfolder] += 1

            ext = Path(member.filename).suffix.lower()
            new_name = f"{idx:05d}_00{ext}"
            dest_path = dest_dir / new_name

            # Extract and write renamed file
            with zf.open(member) as source, open(dest_path, 'wb') as target:
                target.write(source.read())

        print(f"\n✅ Done! Extracted and renamed {len(members)} images.")
        print(f"Output folder: {output_root}")
        print("Subfolders created:")
        for sub in sorted(subfolder_counters.keys()):
            print(f"  {sub}: {subfolder_counters[sub] - 1} images")

# Run the function
extract_and_rename_kamiz(ZIP_PATH, OUTPUT_ROOT, TARGET_CLASS)

!zip -r /content/kamiz_renamed.zip /content/kamiz_renamed

!cp -r /content/kamiz_renamed /content/drive/MyDrive/

"""**Kurti**"""

#kurti
import zipfile
from pathlib import Path
from tqdm import tqdm

# ========== CONFIGURATION ==========
ZIP_PATH = "/content/drive/MyDrive/rename/Train.zip"   # ← CHANGE THIS
OUTPUT_ROOT = "/content/kurti_renamed"        # Where renamed Kurti will go
TARGET_CLASS = "kurti"                        # Top folder inside zip
INTERMEDIATE_FOLDER = "Final Kurti+ Panjabi for Women"   # The folder after Kurti
# ===================================

def extract_and_rename_kurti(zip_path, output_root, target_class, intermediate):
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as zf:
        # Build the expected path pattern: target_class / intermediate / output / any_subfolder / image
        # We'll collect files that match this structure (with or without a 'train/' prefix)
        members = []
        for member in zf.infolist():
            if member.is_dir():
                continue
            parts = Path(member.filename).parts
            # Case 1: No top-level 'train' folder: Kurti/Final.../output/...
            if len(parts) >= 4 and parts[0] == target_class and parts[1] == intermediate and parts[2] == "output":
                members.append(member)
            # Case 2: With 'train' at start: train/Kurti/Final.../output/...
            elif len(parts) >= 5 and parts[1] == target_class and parts[2] == intermediate and parts[3] == "output":
                members.append(member)

        if not members:
            print(f"❌ No files found under '{target_class}/{intermediate}/output/*/'. Check the zip structure.")
            print("Here are the first 20 entries in the zip for debugging:")
            with zipfile.ZipFile(zip_path, 'r') as zf_debug:
                for i, name in enumerate(zf_debug.namelist()[:20]):
                    print(f"  {name}")
            return

        # Counters per subfolder (e.g., folder1, folder2, ...)
        subfolder_counters = {}

        for member in tqdm(members, desc=f"Extracting {target_class}"):
            parts = Path(member.filename).parts
            # Find the subfolder name (the one directly under 'output')
            # Locate the index of 'output' in the parts list
            try:
                output_idx = parts.index("output")
                subfolder = parts[output_idx + 1]   # e.g., 'agnostic'
            except (ValueError, IndexError):
                print(f"Skipping unexpected path: {member.filename}")
                continue

            dest_dir = output_root / subfolder
            dest_dir.mkdir(parents=True, exist_ok=True)

            # Get next index for this subfolder
            if subfolder not in subfolder_counters:
                existing = len(list(dest_dir.glob("*")))
                subfolder_counters[subfolder] = existing + 1
            idx = subfolder_counters[subfolder]
            subfolder_counters[subfolder] += 1

            ext = Path(member.filename).suffix.lower()
            new_name = f"{idx:05d}_00{ext}"
            dest_path = dest_dir / new_name

            # Extract and write renamed file
            with zf.open(member) as source, open(dest_path, 'wb') as target:
                target.write(source.read())

        print(f"\n✅ Done! Extracted and renamed {len(members)} images.")
        print(f"Output folder: {output_root}")
        print("Subfolders created:")
        for sub in sorted(subfolder_counters.keys()):
            print(f"  {sub}: {subfolder_counters[sub] - 1} images")

# Run the function
extract_and_rename_kurti(ZIP_PATH, OUTPUT_ROOT, TARGET_CLASS, INTERMEDIATE_FOLDER)

!zip -r /content/kurti_renamed.zip /content/kurti_renamed
!cp -r /content/kurti_renamed /content/drive/MyDrive/

"""**Panjabi**"""

import zipfile
from pathlib import Path
from tqdm import tqdm

# ========== CONFIGURATION ==========
ZIP_PATH = "/content/drive/MyDrive/rename/Train.zip"   # ← CHANGE THIS
OUTPUT_ROOT = "/content/panjabi_renamed"       # Where renamed Panjabi will go
TARGET_CLASS = "Panjabi for men"               # Exact name as in the zip (case‑sensitive)
# ===================================

def extract_and_rename_panjabi(zip_path, output_root, target_class):
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    with zipfile.ZipFile(zip_path, 'r') as zf:
        # Collect files that match: target_class / output / any_subfolder / image
        # Also handles optional 'train/' prefix at the beginning
        members = []
        for member in zf.infolist():
            if member.is_dir():
                continue
            parts = Path(member.filename).parts
            # Case 1: No top-level 'train' folder: Panjabi for men/output/...
            if len(parts) >= 3 and parts[0] == target_class and parts[1] == "output":
                members.append(member)
            # Case 2: With 'train' at start: train/Panjabi for men/output/...
            elif len(parts) >= 4 and parts[1] == target_class and parts[2] == "output":
                members.append(member)

        if not members:
            print(f"❌ No files found under '{target_class}/output/*/'. Check the zip structure.")
            print("Here are the first 20 entries in the zip for debugging:")
            with zipfile.ZipFile(zip_path, 'r') as zf_debug:
                for i, name in enumerate(zf_debug.namelist()[:20]):
                    print(f"  {name}")
            return

        # Counters per subfolder (the 9 folders inside 'output')
        subfolder_counters = {}

        for member in tqdm(members, desc=f"Extracting {target_class}"):
            parts = Path(member.filename).parts
            # Find the subfolder name directly under 'output'
            try:
                output_idx = parts.index("output")
                subfolder = parts[output_idx + 1]   # e.g., 'agnostic'
            except (ValueError, IndexError):
                print(f"Skipping unexpected path: {member.filename}")
                continue

            dest_dir = output_root / subfolder
            dest_dir.mkdir(parents=True, exist_ok=True)

            # Get next index for this subfolder
            if subfolder not in subfolder_counters:
                existing = len(list(dest_dir.glob("*")))
                subfolder_counters[subfolder] = existing + 1
            idx = subfolder_counters[subfolder]
            subfolder_counters[subfolder] += 1

            ext = Path(member.filename).suffix.lower()
            new_name = f"{idx:05d}_00{ext}"
            dest_path = dest_dir / new_name

            # Extract and write renamed file
            with zf.open(member) as source, open(dest_path, 'wb') as target:
                target.write(source.read())

        print(f"\n✅ Done! Extracted and renamed {len(members)} images.")
        print(f"Output folder: {output_root}")
        print("Subfolders created:")
        for sub in sorted(subfolder_counters.keys()):
            print(f"  {sub}: {subfolder_counters[sub] - 1} images")

# Run the function
extract_and_rename_panjabi(ZIP_PATH, OUTPUT_ROOT, TARGET_CLASS)

!zip -r /content/panjabi_renamed.zip /content/panjabi_renamed
!cp -r /content/panjabi_renamed /content/drive/MyDrive/